import { v4 as uuidv4 } from "uuid";

export const productsList = [
  {
    id: uuidv4(),
    title: "Smart Air Conditioner",
    price: 599.99,
    desc: "Energy-efficient smart AC with WiFi connectivity, voice control, and automatic temperature adjustment based on room occupancy.",
    img: "https://placehold.co/800x600",
  },
  {
    id: uuidv4(),
    title: "Bladeless Ceiling Fan",
    price: 299.99,
    desc: "Ultra-quiet bladeless ceiling fan with LED light, remote control, and six speed settings for optimal comfort.",
    img: "https://placehold.co/700x700",
  },
  {
    id: uuidv4(),
    title: "5G Smartphone",
    price: 999.99,
    desc: "Latest 5G smartphone with a 6.7-inch OLED display, 108MP camera, 5000mAh battery, and 256GB storage.",
    img: "https://placehold.co/600x800",
  },
  {
    id: uuidv4(),
    title: "Gaming Laptop",
    price: 1599.99,
    desc: "High-performance gaming laptop with 15.6-inch 144Hz display, RTX 3070 GPU, 32GB RAM, and 1TB SSD.",
    img: "https://placehold.co/900x600",
  },
  {
    id: uuidv4(),
    title: "Noise-Cancelling Headphones",
    price: 349.99,
    desc: "Premium wireless headphones with adaptive noise cancellation, 30-hour battery life, and high-resolution audio support.",
    img: "https://placehold.co/650x650",
  },
  {
    id: uuidv4(),
    title: "Fitness Smartwatch",
    price: 249.99,
    desc: "Advanced fitness tracker with GPS, heart rate monitor, sleep tracking, and 14-day battery life in a waterproof design.",
    img: "https://placehold.co/500x500",
  },
  {
    id: uuidv4(),
    title: "4K Tablet",
    price: 649.99,
    desc: "Powerful tablet with 12.9-inch 4K display, stylus support, octa-core processor, and 128GB expandable storage.",
    img: "https://placehold.co/800x500",
  },
  {
    id: uuidv4(),
    title: "Portable Bluetooth Speaker",
    price: 129.99,
    desc: "Rugged, waterproof Bluetooth speaker with 360-degree sound, 20-hour playtime, and built-in power bank functionality.",
    img: "https://placehold.co/450x600",
  },
  {
    id: uuidv4(),
    title: "Next-Gen Gaming Console",
    price: 499.99,
    desc: "Latest gaming console supporting 4K gaming at 120fps, ray tracing, and backward compatibility with an extensive game library.",
    img: "https://placehold.co/700x400",
  },
  {
    id: uuidv4(),
    title: "Mirrorless Digital Camera",
    price: 1299.99,
    desc: "Professional-grade mirrorless camera with 45MP full-frame sensor, 8K video recording, and advanced autofocus system.",
    img: "https://placehold.co/750x550",
  },
  {
    id: uuidv4(),
    title: "Smart Refrigerator",
    price: 2499.99,
    desc: "Internet-connected refrigerator with touchscreen display, interior cameras, and AI-powered food management system.",
    img: "https://placehold.co/600x900",
  },
  {
    id: uuidv4(),
    title: "Robot Vacuum Cleaner",
    price: 399.99,
    desc: "Intelligent robot vacuum with LIDAR navigation, multi-floor mapping, and automatic dirt disposal for hands-free cleaning.",
    img: "https://placehold.co/550x550",
  },
  {
    id: uuidv4(),
    title: "4K OLED TV",
    price: 1799.99,
    desc: "65-inch 4K OLED TV with HDR, 120Hz refresh rate, and AI-enhanced picture and sound quality for immersive viewing.",
    img: "https://placehold.co/1000x600",
  },
  {
    id: uuidv4(),
    title: "Smart Door Lock",
    price: 249.99,
    desc: "Keyless smart lock with fingerprint recognition, smartphone control, and temporary access codes for guests.",
    img: "https://placehold.co/400x600",
  },
  {
    id: uuidv4(),
    title: "Wireless Earbuds",
    price: 179.99,
    desc: "True wireless earbuds with active noise cancellation, transparency mode, and wireless charging case for all-day use.",
    img: "https://placehold.co/500x400",
  },
  {
    id: uuidv4(),
    title: "Electric Scooter",
    price: 599.99,
    desc: "Foldable electric scooter with 25-mile range, 15.5mph top speed, and app connectivity for urban commuting.",
    img: "https://placehold.co/700x900",
  },
  {
    id: uuidv4(),
    title: "Smart Thermostat",
    price: 199.99,
    desc: "Energy-saving smart thermostat with learning capabilities, smartphone control, and compatibility with voice assistants.",
    img: "https://placehold.co/450x450",
  },
  {
    id: uuidv4(),
    title: "Mesh WiFi System",
    price: 349.99,
    desc: "Whole-home mesh WiFi system with tri-band technology, parental controls, and easy setup for seamless coverage.",
    img: "https://placehold.co/600x500",
  },
  {
    id: uuidv4(),
    title: "Espresso Machine",
    price: 599.99,
    desc: "Semi-automatic espresso machine with built-in grinder, milk frother, and programmable settings for cafe-quality coffee at home.",
    img: "https://placehold.co/750x600",
  },
  {
    id: uuidv4(),
    title: "Smart Garden",
    price: 199.99,
    desc: "Indoor smart garden with LED grow lights, self-watering system, and app control to grow fresh herbs and vegetables year-round.",
    img: "https://placehold.co/650x500",
  },
  {
    id: uuidv4(),
    title: "Portable Power Station",
    price: 999.99,
    desc: "High-capacity portable power station with AC outlets, USB ports, and solar charging capability for outdoor adventures and emergencies.",
    img: "https://placehold.co/800x500",
  },
  {
    id: uuidv4(),
    title: "3D Printer",
    price: 449.99,
    desc: "User-friendly 3D printer with auto-leveling bed, resume printing function, and large build volume for creative projects.",
    img: "https://placehold.co/700x600",
  },
  {
    id: uuidv4(),
    title: "Smart Doorbell",
    price: 179.99,
    desc: "HD video doorbell with two-way audio, night vision, motion detection, and cloud storage for enhanced home security.",
    img: "https://placehold.co/400x700",
  },
  {
    id: uuidv4(),
    title: "Wireless Gaming Mouse",
    price: 149.99,
    desc: "High-precision wireless gaming mouse with 25,000 DPI optical sensor, programmable buttons, and RGB lighting.",
    img: "https://placehold.co/550x400",
  },
  {
    id: uuidv4(),
    title: "Smart Light Bulbs Set",
    price: 99.99,
    desc: "Set of 4 color-changing smart LED bulbs with millions of colors, scheduling, and voice control compatibility.",
    img: "https://placehold.co/600x450",
  },
  {
    id: uuidv4(),
    title: "Ultrawide Monitor",
    price: 799.99,
    desc: "34-inch curved ultrawide monitor with 3440x1440 resolution, 144Hz refresh rate, and HDR support for immersive productivity and gaming.",
    img: "https://placehold.co/900x500",
  },
  {
    id: uuidv4(),
    title: "Smart Scale",
    price: 79.99,
    desc: "Bluetooth-connected smart scale measuring weight, body fat, muscle mass, and more, syncing data with fitness apps.",
    img: "https://placehold.co/500x600",
  },
  {
    id: uuidv4(),
    title: "Drone with 4K Camera",
    price: 799.99,
    desc: "Foldable drone with 4K camera, 3-axis gimbal, 30-minute flight time, and intelligent flight modes for stunning aerial photography.",
    img: "https://placehold.co/800x450",
  },
  {
    id: uuidv4(),
    title: "Portable SSD",
    price: 199.99,
    desc: "1TB portable SSD with USB-C connectivity, 1050MB/s read speeds, and durable, shock-resistant design for fast, reliable storage on-the-go.",
    img: "https://placehold.co/450x350",
  },
];
